-- Supabase schema for TFZ Labo CRM

-- 1. TABELLA CLIENTI
CREATE TABLE public.clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    email text,
    phone_whatsapp text,
    m3u_code text, -- Codice M3U del cliente
    mac_address text, -- Indirizzo MAC del dispositivo
    device_key text, -- Chiave del dispositivo
    paid_amount decimal(10,2), -- Prezzo pagato
    notes text,
    status text CHECK (status IN ('active', 'inactive', 'banned')) DEFAULT 'active',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 2. TABELLA ABBONAMENTI
CREATE TABLE public.subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint REFERENCES public.clients(id) ON DELETE CASCADE,
    username_iptv text NOT NULL,
    password_iptv text,
    server_url text,
    price decimal(10,2), -- Prezzo dell'abbonamento
    start_date timestamptz NOT NULL,
    end_date timestamptz NOT NULL, -- Fondamentale per le scadenze
    package_name text,
    is_trial boolean DEFAULT false,
    active boolean DEFAULT true,
    created_at timestamptz DEFAULT now()
);

-- 3. TABELLA EVENTI TIMELINE (Per lo storico azioni)
CREATE TABLE public.timeline_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint REFERENCES public.clients(id) ON DELETE CASCADE,
    event_type text CHECK (event_type IN ('creation', 'renewal', 'alert_sent', 'support', 'note')),
    description text,
    created_at timestamptz DEFAULT now()
);

-- 4. TABELLA TICKETS
CREATE TABLE public.tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint REFERENCES public.clients(id) ON DELETE CASCADE,
    subject text NOT NULL,
    status text CHECK (status IN ('open', 'working', 'closed')) DEFAULT 'open',
    created_at timestamptz DEFAULT now()
);

-- ABILITAZIONE ROW LEVEL SECURITY (Opzionale ma consigliato per sicurezza)
-- Per ora lo lasciamo disabilitato per facilitare lo sviluppo,
-- ma in produzione dovrai attivare le Policy.
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timeline_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- CREAZIONE POLICY PER ACCESSO LIBERO (SOLO PER SVILUPPO)
-- Attenzione: questo permette a chiunque abbia le chiavi anonime di leggere/scrivere.
-- Rimuovi queste policy quando aggiungerai il Login/Auth.
CREATE POLICY "Enable all access for all users" ON public.clients FOR ALL USING (true);
CREATE POLICY "Enable all access for all users" ON public.subscriptions FOR ALL USING (true);
CREATE POLICY "Enable all access for all users" ON public.timeline_events FOR ALL USING (true);
CREATE POLICY "Enable all access for all users" ON public.tickets FOR ALL USING (true);
